<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>QH-TDS</AssemblyName>
    <ApplicationIcon>iconfinder-social-media-web-network-logo02-4584667_122300.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="iconfinder-social-media-web-network-logo02-4584667_122300.ico" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="obj\**\*.cs" />
    <Compile Remove="bin\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Leaf.xNet" Version="5.2.10" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="SunnyUI" Version="3.9.4" />
  </ItemGroup>

</Project>
